### ISSUE TITLE
Errors in data preprocessing

### ISSUE THREAD

**Issue by lihx-me** [antoinedelplace/MIMO-unofficial#2]
python mimo/dataset_preprocessing/get_apose_ref.py, I get an error.

Exception: File ./MIMO/data_demo/a_pose_raw.png does not exist.

Could you provide more detailed data preparation?

**Comment by antoinedelplace** [comment]
Sure! You need to provide the A pose in which all avatars will be reposed.

You can for example use this image: 
![a_pose_raw](https://github.com/user-attachments/assets/46e3d732-c50c-4463-9f87-7845a818e9cb)
